### ISSUE TITLE
ERROR: mod_adele: Verlinkung funktioniert nicht, wenn Moodle nicht im Root

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-mod_adele#3]
<img width="385" alt="grafik" src="https://github.com/user-attachments/assets/1b1ded73-0951-4503-8beb-4f370658a73b">
führt zu
<img width="348" alt="grafik" src="https://github.com/user-attachments/assets/cbb3c02a-0038-4501-b442-1336de1b0b79">

**Comment by ralferlebach** [comment]
![Image](https://github.com/user-attachments/assets/8efc1b91-bcc6-42e9-88bf-e24f840b6cb1)

**Comment by WunderJacob** [comment]
Hi @ralferlebach , eigentlich sollten jetzt alle Links den prefix vom $CFG->wwwroot haben. Kannst du nochmal schauen ob es bei dir funktioniert?

**Comment by ralferlebach** [comment]
Im mod_form funktionert es nocht. Ich fixe es mal schnell selbst:
https://github.com/Wunderbyte-GmbH/moodle-mod_adele/pull/4

**Comment by ralferlebach** [comment]
Es gibt darüber hinaus noch immer fehlerhafte Verlinkungen in local_adele.

Bitte prüft ggf. mit einem Tool wie EasyFind (für Mac) verzeichnisweit für mod_adele sowie local_adele, wo sich im Quelltext Links finden lassen. Danke.

<img width="825" alt="grafik" src="https://github.com/user-attachments/assets/7bd7c1ce-a2f0-4744-b8f4-6583c8e0687d">
<img width="948" alt="grafik" src="https://github.com/user-attachments/assets/49865f72-b806-4007-936d-767bc0794e2e">
