### ISSUE TITLE
ERROR: vorausgewählter Lernpfad bei Neuanlegung

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/moodle-mod_adele#6]
Beschreibung:

Lernpfad als neue Aktivität für einen Kurs auswählen

erwartetes Ergebnis:
Nutzer kann (bzw. muss) Lernpfad auswählen (und wenn dies nicht geschieht, gibt es eine entsprechende Rückmeldung)

tatsächliches Ergebnis:
**irgendein** Lernpfad ist bereits eingetragen (Folge: der Nutzer wird nicht informiert, dass ggf. seine Absicht anders als erwartet eingestellt und umgesetzt wird und wundertz sich über das Verhalten des Plugins)
<img width="535" alt="grafik" src="https://github.com/user-attachments/assets/204f2d60-aafa-41cf-b963-4fd152239319">

**Comment by WunderJacob** [comment]
Default ist jetzt leer und required
